### ISSUE TITLE
MSF-3 Review docs/MainScreen.md

### ISSUE THREAD

**Issue by geka32** [geka32team/moonshot-jam-2020-front#7]
@Smira87 to review and correct English version:
- [x] create a new branch MSF-3 based on main one
- [x] make your changes into docs/MainScreen.md file
- [x] commit your changes into MSF-3 branch
- [x] create a pull-request based on MSF-3 branch
- [x] link your pull-request into this issue
- [x] @Smira87 - you can do it!!!

**Comment by Smira87** [comment]
let me try

**Comment by Smira87** [comment]
Done

**Comment by geka32** [comment]
@Smira87 when your pull-request is ready move the issue card into Review.
Do not close it by yourself, as your work/changes will be lost.

**Comment by geka32** [comment]
@Smira87 I really do not see any changes in your PR except "Hello world" sentence.
The main goal of this issue is "to review and correct English version".
Please follow up. When PR is ready move this issue into Review column.
Do not merge your branch into main one.

**Comment by Smira87** [comment]
I have added task levels to the end of file.
